services:
  - type: web
    name: skillpulse-sas
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 5001
